config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'books#top'
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class =true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title,
  presence: true

  validates :body,
  presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end

  def index
    @books = Book.all
    @book = Book.new
  end


  def create
    @book = Book.new(book_params)

    if @book.save
      flash[:notice] = "Book was successfully created"
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render action: :index
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated"
      redirect_to book_path(@book)
    else
      render action: :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_with model:@book, local: true do |f| %>

  <% if flash[:notice] %>
   <p id="notice">
       <%= flash[:notice] %>
   </p>
  <% end %>

  <% if @book.errors.any? %>
  <%= "error" %>
    <div>
      <ul style="color: red">
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Update Book' %>
<% end %>


<%= link_to "Show", book_path %>
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<h1>Books</h1>

<table>
 <thead>
  <tr>
   <th>Title</th>
   <th>Body</th>
   <th colspan="3"></th>
  </tr>
 </thead>

 <tbody>
  <% @books.each do |book| %>
   <tr>
    <td><%= book.title %></td>
    <td><%= book.body %></td>
    <td><%= link_to "Show", book_path(book.id) %></td>
    <td><%= link_to "Edit", edit_book_path(book.id) %></td>
    <td><%= link_to "Destroy", book_path(book.id), method: :delete %></td>
   </tr>
  <% end %>
 </tbody>
</table>



<h2>New book</h2>
<%= form_with model:@book, local:true do |f| %>
  <% if flash[:notice] %>
   <p id="notice">
       <%= flash[:notice] %>
   </p>
  <% end %>

  <% if @book.errors.any? %>
  <%= "error" %>
    <div>
      <ul style="color: red">
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <p id="notice">
    <%= flash[:notice] %>
  </p>
<% end %>

<h3>Title:</h3>
<p><%= @book.title %></p>

<h3>Body:</h3>
<p><%= @book.body %></p>


<%= link_to "Edit", edit_book_path(@book) %>
<%= link_to "Back", books_path %>

app/views/books/top.html.erb
<h1>ようこそ　Bookersへ！</h1>

　<p>Bookers では、さまざまな書籍に関するあなたの意見や</p>

　<p>印象を共有し交換する事ができます</p>


<%= link_to "start", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>